name: Build Android

on:
  workflow_dispatch:
    inputs:
      exportType:
        required: true
        type: choice
        default: "androidPackage"
        options:
          - androidPackage
          - androidAppBundle

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      # 查看repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          reposity: ${{secrets.REPO_NAME}}
          lfs: true # 使用 LFS

      # Cache可以讓你之後Build更快
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # 用Game-CI Builder建置專案
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          androidExportType: ${{ inputs.exportType }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

      # 輸出成artifact
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
          retention-days: 1

      # - name: Discord Notify
      #   uses: tsickert/discord-webhook@v5.3.0
      #   with:
      #     webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     content: "### New build action completed!"
      #     filename: build
